name: lazy_refreshing_listview
description: "A flutter package to handle listview with refresh, and lazy scrolling smartly"
version: 0.0.3
homepage: https://github.com/faysalewucse/lazy_refreshing_listview

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  pull_to_refresh_flutter3: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
